language: java
before_script:
  - psql -c 'create database pproval;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: pproval
jdk: oraclejdk11
notifications:
  email: false
services:
  - postgresql
