server:
  port: 3000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pproval-test
    username: postgres
    password:
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        temp:
          use_jdbc_metadata_defaults: false

---

spring:
  profiles: prod
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        temp:
          use_jdbc_metadata_defaults: false
